### ISSUE TITLE
ouath2 auth from geoserver uses wrong URL

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-demo#15]
The oauth endpoint (GeoNode) URL in Geoserver is not correctly configured. If you try to access Geoserver using GeoNode authentication you're directed to an internal IP. See image below:

![image](https://user-images.githubusercontent.com/571129/39566577-5430b4c2-4ebc-11e8-8445-5c50f9a30394.png)

**Comment by cezio** [comment]
This should work now
