### ISSUE TITLE
Connection Error when adding a layer directly from the Map.

### ISSUE THREAD

**Issue by fouad-semaan** [geosolutions-it/geonode-demo#16]
![image](https://user-images.githubusercontent.com/38422316/39566603-7177dbc8-4ebc-11e8-8b6f-94d34b8890b8.png)

Details in the link below: 
master.demo.geonode.org/geoserver/wms

**Comment by cezio** [comment]
This should work now. please verify

**Comment by fouad-semaan** [comment]
Tested! It works. Thanks.
