### ISSUE TITLE
Integrate restore with entrypoint

### ISSUE THREAD

**Issue by cezio** [geosolutions-it/geonode-demo#25]
At the moment, when django container is restarted or whole docker is restarted, customizations to auth (`admin` user to be precise, other users created and restored will be preserved as-is) will be lost, because entrypoint script will load default fixtures. 

To avoid that, we can copy restore fixtures to persistent volume and let entrypoint load it, so restarts won't harm deployment auth.

**Comment by giohappy** [comment]
If I understand it correctly, we chould somthing like we do for geonode-generic https://github.com/geosolutions-it/geonode-generic/blob/master/entrypoint.sh#L22
