### ISSUE TITLE
Enable 'geonode.importer' Uploader instead of the old 'geonode.rest' one

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode-demo#33]
This would allow us to upload more data formats, support for temporal serie and pre-processing of GeoTiffs (in the future).

In order to enable this feature, we will need GeoServer to be able to use a PostGIS datastore.

**Comment by giohappy** [comment]
I would automate it using the same env var being used by geonode itseld to define the backend DB: 

- https://github.com/geosolutions-it/geonode/blob/master/geonode/settings.py#L120
- https://github.com/geosolutions-it/geonode/blob/master/geonode/settings.py#L766

**Comment by giohappy** [comment]
Fixed in #35
